### ISSUE TITLE
Not on crates!?

### ISSUE THREAD

**Issue by Hoverbear** [james-darkfox/rs-scoped_log#3]
This should be on Crates! It's so useful!

**Comment by james-darkfox** [comment]
Indeed, it was a little unstable at the time I first considered uploading. And after several versions for the wrapped_enum crate already. Just wanted to make sure that it was stable before the first 0.1.0 release.

Thanks for bumping the issue. Seems stable enough - at least for now. I will publish when @danburkert adds himself to the Cargo.toml.

:-)

**Comment by james-darkfox** [comment]
https://crates.io/scoped_log
